#!/bin/bash
DIR=$(pwd)			


if [ "$1" == "-c" ] 
then
	
	echo "Clean up.."
	rm -rfv P1/build-dir/*
	rm -rfv P2/build-dir/*

elif [ "$1" == "-p" ]		
then
	if ! [[ "$2" =~ ^[0-9]+$ ]]
	then
		echo "Error in inputs. -p must be followed by an Integer [0-100]..."
	else
		if [ "$2" -lt "0" ] ||  [ "$2" -gt  "100" ]
		then
			echo "Propability must be [0-100]"
		else
			echo "Running project.."

			echo "CMake Building for P1.."
			cd P1
			mkdir build-dir
			cd build-dir
			cmake ..
			echo "CMake Build done"
			echo "Build project..."
			make
			echo "Build done..."


			cd ../../

			echo "CMake Building for P2.."
			cd P2
			mkdir build-dir
			cd build-dir
			cmake ..
			echo "CMake Build done"
			echo "Build project..."
			make
			echo "Build done..."
			gnome-terminal -e ./Com_P2

			cd ../../
			cd P1
			cd build-dir
			./Com_P1 '$2'
		fi
	fi

else
	echo "Missing arguments... [ -c, -p ]"
fi


